FROM golang:1.25.1-alpine AS builder

WORKDIR /src
RUN apk add --no-cache git

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN CGO_ENABLED=0 go build -ldflags="-s -w" -o streamoid main.go

FROM alpine:3.22
WORKDIR /

RUN addgroup -S appgroup && adduser -S appuser -G appgroup

COPY --from=builder --chown=appuser:appgroup /src/streamoid /streamoid
COPY --from=builder --chown=appuser:appgroup /src/temp /temp

USER appuser

EXPOSE 8080
CMD ["./streamoid"]